name: Expo EAS Build (Android Production)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install EAS CLI
        run: npm install -g eas-cli@latest

      - name: Verify EAS CLI version
        run: eas --version

      - name: Debug EXPO_TOKEN
        run: echo "EXPO_TOKEN is set"

      - name: Verify EAS login
        run: eas whoami

      - name: Install dependencies
        working-directory: altaviz_mobile
        run: npm install

      - name: Build Android app (Production)
        working-directory: altaviz_mobile
        run: eas build --platform android --profile production --non-interactive
