name: Expo EAS Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: List repository contents
        run: ls -la
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install EAS CLI
        run: npm install -g eas-cli
      
      - name: Setup Expo token
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: echo "EXPO_TOKEN=$EXPO_TOKEN" >> $GITHUB_ENV
      
      - name: Authenticate with EAS
        run: eas login --non-interactive
      
      - name: Install dependencies
        working-directory: altaviz_mobile
        run: npm install
      
      - name: Verify login
        run: eas whoami
      
      - name: Build app
        working-directory: altaviz_mobile
        run: eas build --profile development --platform android --non-interactive
